// import React from "react"

import { Metadata } from "next"

interface Props {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: "Xenz Feed",
    description: "Generated by create next app",
}

async function layout({ children }: Props) {
  return (
    <div>
        <h1>Layout</h1>
        {children}
    </div>
  )
}

export default layout